
# Secured Properties
dynamodb:
  accesskey: "![n1z+OPkpA1Jsc+RzqqWMxyhKb+88ORWlzlCrkOMDuoo=]"
  secretkey: "![CdTrP88+5PVUwd9LLoWYt7mj4kCZn3WCjpmwFhx5I+q8FLN7pmysdfDuJ/aMQ0YZ]"

titan:
 sftp:
  username: "![ZibIQHduKBhWhwM1G4K8VA==]" 
  password: "![EO09WjxFFEVguFoFeXdW3A==]"

# ClientId and ClientSecret of digigoldOrderPAPI to be used in all the Outbound Calls to API's
digigold-order-papi: 
  clientId: "![WBrD6JW/RmSIv6EAk1Pl/p56Vi0kDFTVO5/sJrlP2g6pq2aTVX8MMLiy4Y69SA+z]"
  clientSecret: "![VMKloGwils2yctHfN8Fb27obH/xSBkFNAScdwbjME3oNvJQSRY1ttO0QLojXZ3WQ]"
  
aes:
  password: "![BKj8cVo3c9xUhGWQptxgCODmgNZJn1a3LvRUru4U6b0=]" 
  
amazon-s3:
  accessKey: "![pnQeXOC5Vpzco0DM7X/zGJKlArfBBR0KXyzd72eQZqo=]"
  secretKey: "![DmY8kgGk/GL68gTYkPZl+Hb07LK7aOqfiXnSSr8Z1+au24DEiMdoZBzAYJoiHdNI]"
  
