##############################
#      Global Properties     #
##############################
global.properties: #TODO FOR DEVELOPER - CHANGE THIS ACCORDING TO THE API INVENTORY
  appName: "digigold-order-papi"
  name: "Digigold Order Process API"
  businessId: "" # Business Operation ID


 
# JSON Logger Properties (should reflect what's on POM) 
#TODO FOR DEVELOPER - CHANGE THIS BASED ON THE POM.XML
json.logger.application:
  name: "digigold-order-papi" #pom > artifactId
  version: "1.0.0"  #pom > version

##############################
#      Global Constants      #
##############################
#global.constants:  #TODO FOR DEVELOPER - ADD IF THERE ARE GLOBAL CONSTANTS TO BE USED

log:
  category: "com.titan.mulesoft"
  
reports:
  oracleReport:
    reportType: "Oracle Report"
    reportSequenceNumber: "0"  
  transactionReport:
    reportType: "Transaction Report" 
#    StartDate: "12/31/2022 0:0:0"
#    EndDate: "01/01/1980 23:59:59"
  transactionConsolidatedReport:
    reportType: "Transaction Consolidated Report" 
    StartDate: "01/01/1980 0:0:0"
#    EndDate: "01/01/1980 23:59:59"
  dropOrderReport:
    reportType: "DropOrder Report" 
#    StartDate: "12/31/2022 0:0:0"
#    EndDate: "01/01/1980 23:59:59"
    batchCount: "3000"
  
#Scheduler Configs
scheduler:
  oracleReportGeneration: "0 0 5 ? * *"
  transactionReportGeneration: "0 0 3 ? * *"
  dropOrderReportGeneration: "0 0 4 ? * *"
  transactionConsolidatedReportGeneration: "0 0 1 1/1 * ? *"
  timeZone: "Asia/Kolkata"
  transactionMigrationSchedule: "0 0 6 ? * *"
   

# Testing changes below - Scheduler Configs
#scheduler:
#  oracleReportGeneration: "0 0 5 ? * *"
#  transactionReportGeneration:   "15" # in minutes
#  dropOrderReportGeneration: "0 0 4 ? * *"  
#  transactionConsolidatedReportGeneration:  "0 0 4 ? * *" 
#  timeZone: "Asia/Kolkata"
#  transactionMigrationSchedule: "0 0 6 ? * *" 
   
api:
  resource: "resource::16d6a22d-7691-4a2e-bbcb-8a81c9c5d4e6:digigold-order-papi:1.0.5:raml:zip:digigold-order-papi.raml"
 
papi:
  connectionIdleTimeOut: "30000"
  responseTimeOut: "50000"
  
createTransactions:
  successMessage: "Transaction posted successfully"
  errorMessage: "Transaction can not be posted now. Please try after some time."
  errorCode: "DIGORDCREPAPI01"

fetchTransactions:
  successMessage: ""
  errorMessage: "Unable to fetch records now. Please try after some time."
  errorCode: "DIGORDFETPAPI01"
  
  
