##############################
#      Global Properties     #
##############################
global.properties: #TODO FOR DEVELOPER - CHANGE THIS ACCORDING TO THE API INVENTORY
  appName: "digigold-order-papi"
  name: "Digigold Order Process API"
  businessId: "" # Business Operation ID

# JSON Logger Properties (should reflect what's on POM) 
#TODO FOR DEVELOPER - CHANGE THIS BASED ON THE POM.XML
json.logger.application:
  name: "digigold-order-papi" #pom > artifactId
  version: "1.0.11"  #pom > version

##############################
#      Global Constants      #
##############################

log:
  category: "com.titan.mulesoft"
 
############################  IMPORANT - To Be used in the environments ###############
reports:
  oracleReport:
    reportType: "Oracle Report"
    reportSequenceNumber: "0"  
  transactionReport:
    reportType: "Transaction Report" 
  transactionConsolidatedReport:
    reportType: "Transaction Consolidated Report" 
    StartDate: "1980-01-01 00:00:00.000"
  dropOrderReport:
    reportType: "DropOrder Report" 
  batchCount: "4000"

dateformat: 
  datadateformat: "yyyy-MM-dd HH:mm:ss.n"
  startdateformat: "yyyy-MM-dd 00:00:00.000"
  enddateformat: "yyyy-MM-dd 23:59:59.000"


scheduler:
  oracleReportGeneration: "0 0 5 ? * *"
  transactionReportGeneration: "0 0 3 ? * *"
  dropOrderReportGeneration: "0 0 4 ? * *"
  transactionConsolidatedReportGeneration: "0 0 1 1,15 * ? *"
  transactionMigrationSchedule: "0 30 0 20 3 ? *"
  timeZone: "Asia/Kolkata"

api:
  resource: "resource::16d6a22d-7691-4a2e-bbcb-8a81c9c5d4e6:digigold-order-papi:1.0.6:raml:zip:digigold-order-papi.raml"
 
papi:
  connectionIdleTimeOut: "30000"
  responseTimeOut: "50000"
  
createTransactions:
  successMessage: "Transaction posted successfully"
  errorMessage: "Transaction can not be posted now. Please try after some time."
  errorCode: "DIGORDCREPAPI01"

fetchTransactions:
  successMessage: ""
  errorMessage: "Unable to fetch records now. Please try after some time."
  errorCode: "DIGORDFETPAPI01"
  
  
