##############################
#      Global Properties     #
##############################
global.properties: #TODO FOR DEVELOPER - CHANGE THIS ACCORDING TO THE API INVENTORY
  appName: "digigold-order-papi"
  name: "Digigold Order PAPI"
  businessId: "c3cf65b1-e732-48c6-b48e-b22effe859fa" # Business Operation ID


 
# JSON Logger Properties (should reflect what's on POM) 
#TODO FOR DEVELOPER - CHANGE THIS BASED ON THE POM.XML
json.logger.application:
  name: "digigold-order-papi-app" #pom > artifactId
  version: "1.0.0"  #pom > version

##############################
#      Global Constants      #
##############################
#global.constants:  #TODO FOR DEVELOPER - ADD IF THERE ARE GLOBAL CONSTANTS TO BE USED

log:
  category: "com.titan.mulesoft"

default:
  reportName: "Oracle Report"
  reportSequenceNumber: "0"
  
until:
  retries: "2"
  millisBetweenRetries: "5000"
  
#Scheduler Configs
scheduler:
  oracleReportGeneration: "0 0 5 ? * *"
  timeZone: "Asia/Kolkata"