# Secured Properties
dynamodb:
  accesskey: "![Sy3Kc5IAA2AwDxOqiVvh4cibGtX1pURa5DxRWq4w33g=]"
  secretkey: "![3+URvPp4/FpM6RxImNbK1vk0rMPkfDnlaON669GXstdbQ8+nQr5jglYpJt4DAce4]"

titan:
 sftp:
  username: "![1wlYy6LeAoO1LhrUIjK6bg==]"
  password: "![RSeGcGuBwIukfXcQen8cCQ==]"

# ClientId and ClientSecret of digigoldOrderPAPI to be used in all the Outbound Calls to API's
digigold-order-papi:
  clientId: "![NZAtrAk41x2AH9FDOVGPf/Z4p3U7x8wxsNsMlULxgPLLw0lNpgJIxXAlj8VFRcv3]"
  clientSecret: "![sjOH/cfK55qDPZzi/Pb/IOA3k1JqFKwa4vzyWP7LuGb6X3hvQQlpx8VUBxNMr1r8]"

aes:
  password: "![uTTFNR8TDJ99u/lDCwqixbYUrkXpAEq1UtPCCJq2JDQ=]"

amazon-s3:
  accessKey: "![iXYiExmpJHTyTkAxCFbOhV1CBDyeSMckKYzti9e8QwU=]"
  secretKey: "![DCV3wDVA3PrOXV/nWt1mWC9z5oUPWshC5MnY1CogZq6c7xMHcbrX0gFEi+uLFUK7]"