###############################
#  INBOUND                    #
###############################

https:
  port: "8081"
  version: "v1"
  path: "/api/${https.version}/*"
  host: "0.0.0.0"

api:
  autodiscovery:
    id: "18585553"


###############################
#  OUTBOUND                   #
###############################

dynamodb:
  regionendpoint: "ap-south-1"
  tableName: "XDG_TRANSACTION"

#Titan SFTP Server 
titan:
 sftp:
  host: "172.30.5.115"
  port: "22"
  csvfilenamepattern: "*.csv"
  xlsxfilenamepattern: "*.xlsx"
  oracleReport: "/home/ECOM_MuleSoft_PROD/mulesoft/order/jewellery/digigold/oraclefeed/"
  transactionReport: "/home/ECOM_MuleSoft_PROD/mulesoft/order/jewellery/digigold/transaction/"
  transactionConsolidatedReport: "/home/ECOM_MuleSoft_PROD/mulesoft/order/jewellery/digigold/transactionConsolidated/"
  dropOrderReport: "/home/ECOM_MuleSoft_PROD/mulesoft/order/jewellery/digigold/droporder/"
  txnMigration:
    migrationfileName: "DigiGoldTransactions.csv"
    workingDir: "/home/ECOM_MuleSoft_PROD/mulesoft/order/jewellery/digigold/migration/input"
    archiveDir: "/home/ECOM_MuleSoft_PROD/mulesoft/order/jewellery/digigold/migration/archive"

  
#COMMON SFTP SAPI

sftp-sapi:
  connectionTimeout: "60000"
  responseTimeout: "60000"
  sourceChannel: "digigoldOrderPAPI"
  host: "sftp-sapi-p53l8f.internal-lvpvl0.sgp-s1.cloudhub.io"
  port: "443"
  basePath: "/api/v1"
  endpoints:
    post:
      sftpWrite: "/write"
      sftpMethod: "POST"
   
#Dynamo Order SAPI
dynamo-sapi:
  connectionTimeout: "60000"
  responseTimeout: "30000"
  sourceChannel: "digigoldOrderPAPI"
  host: "dynamo-order-sapi-xuyk1p.internal-lvpvl0.sgp-s1.cloudhub.io"
  port: "443"
  basePath: "/api/v1"
  endpoints:
    get:
      transactionsPath: "/transactions"
      transactionsMethod: "GET"
    post:
      transactionsPath: "/transactions"
      transactionsMethod: "POST"

    
#COMMON Notification SAPI
notification-sapi:
  connectionTimeout: "60000"
  responseTimeout: "60000"
  sourceChannel: "digigoldOrderPAPI"
  host: "notification-sapi-p53l8f.internal-lvpvl0.sgp-s1.cloudhub.io"
  port: "443"
  basePath: "/api/v1"
  endpoints:
    post:
      notificationPath: "/notifications"
      notificationMethod: "POST"
      queryParameter: "Email"
      
# SFCC Order SAPI
sfcc-order-sapi:
  connectionTimeout: "60000"
  responseTimeout: "30000"
  sourceChannel: "digigoldOrderPAPI"
  host: "sfcc-order-sapi-p53l8f.internal-lvpvl0.sgp-s1.cloudhub.io"
  port: "443"
  basePath: "/api/v1"
  endpoints:
    post:
      customerSearchPath: "/customer/search"
      notificationMethod: "POST"
  batchSize: "25"

#Notification Email for Reports
reportsEmail:
  to: "jeevanandhamanbu@titan.co.in,sravanijonna@titan.co.in,suwathi@titan.co.in,nehajain@titan.co.in"
  from: "ecomas@titan.co.in"
  cc: "sravanijonna@titan.co.in"
  ErrorSubject: "Generation Failure Notification "
  Subject: "Generation Notification "
  contentType: "text/html"
  body: "Please find the attachment of the report generated "
  noDataBody: "There is no data to generate "
  
  
order-papi:
  buyConfirmed:
    debit: "245154"
    credit: "153891"
  redemption:
    debit: "245170"
    credit: "151633"


until:
  retries: "2"
  millisBetweenRetries: "3000"

amazon-s3:
  regionEndpoint: "ap-south-1"
  bucket: "mule-titan-dg-prd"
