###############################
#  INBOUND                    #
###############################
api:
  autodiscovery:
    id: "" #TODO FOR DEVELOPER - CHANGE ACCORDINGLY THE DEFAULT CONFIGURATION

###############################
#  OUTBOUND                   #
###############################
dynamodb:
  regionendpoint: "ap-south-1"

titan:
 sftp:
  host: "172.30.5.115"
  port: "22"
  workingdir: "/home/ECOM_MuleSoft/mulesoft/dev/order/jewellery/digigold/migration/input"
  filenamepattern: "*.csv"
  archivedir: "/home/ECOM_MuleSoft/mulesoft/dev/order/jewellery/digigold/migration/archive"
  pollingfrequency: "10" # in Minutes