# Secured Properties
dynamodb:
  accesskey: "![n1z+OPkpA1Jsc+RzqqWMxyhKb+88ORWlzlCrkOMDuoo=]"
  secretkey: "![CdTrP88+5PVUwd9LLoWYt7mj4kCZn3WCjpmwFhx5I+q8FLN7pmysdfDuJ/aMQ0YZ]"
titan:
 sftp:
  username: "![ZibIQHduKBhWhwM1G4K8VA==]" 
  password: "![EO09WjxFFEVguFoFeXdW3A==]"