
# Secured Properties
dynamodb:
  accesskey: "![zWjGkmCtJxw6Fzs/R70znRIufqrqqdzfr9eUIiFOCX4=]"
  secretkey: "![qjPMFXJHyDLwx1Iporh06p0eKxB7EafGr82823zATdinOvjaEsg9Nhni/vB93rVZ]"

titan:
 sftp:
  username: "![Rv7n7WqWot/COLi99oeGnc+Jd2rQOZRZ1Wwubvt7Lto=]"
  password: "![tW/NQfC4+o97FkLpjKi+sA==]"

# ClientId and ClientSecret of digigoldOrderPAPI to be used in all the Outbound Calls to API's
digigold-order-papi:
  clientId: "![7bl6bbu7YLgC6F5uqTrXoIk02tkHYP+JoD9xpLje8rjQI8x3zmY8+hS7e+vtwh6E]"
  clientSecret: "![e6Uq9bxnEeeyBDn1cXmDlCEYKHPfjP+0wXAHU5OEGsVtNJynTolO6oThfgbcrtmS]"

aes:
  password: "![a5HDCYNrbDISortTmn4thkQ3cXwHb4KLcs9Zr9eF/AA=]"

# Secured Properties
smtp:
  password: "![261VqBbmutYGr479O8LCCA==]"
  clientsecret : "![MRbRyVVzIjoE03a3z+3vimfIzkU7A+YWFuLsHF/y7SNqWJkbS3yf/WXGAf+YRNkq]"

amazon-s3:
  accessKey: "![8g4E+twk9RBFv52NtjpfcdiOfNfkieKLxMxnf0DNRYY=]"
  secretKey: "![Vh29KoToBHzS3hepEDgikKDuJJZAEdWi2L3GcnRGm/dhs+hMXO9/NUQC2vQvj9Be]"