
# Secured Properties
dynamodb:
  accesskey: "![PleaseinsertEncryptedPwd]"
  secretkey: "![PleaseinsertEncryptedPwd]"

titan:
 sftp:
  username: "![PleaseinsertEncryptedPwd]" 
  password: "![PleaseinsertEncryptedPwd]"

# ClientId and ClientSecret of digigoldOrderPAPI to be used in all the Outbound Calls to API's
digigold-order-papi: 
  clientId: "![PleaseinsertEncryptedPwd]"
  clientSecret: "![PleaseinsertEncryptedPwd]"
  
aes:
  password: "![PleaseinsertEncryptedPwd]" 
  
