###############################
#  INBOUND                    #
###############################
api:
  autodiscovery:
    id: "18549439"

###############################
#  OUTBOUND                   #
###############################


#SAMPLE EXTERNAL SYSTEM
dynamoOrderSapi:
  host: "dynamo-order-sapi-dev-230pwz.internal-1zj8l2.sgp-s1.cloudhub.io"
  port: "443"
  basepath: "/api/v1/"
  endpoint: "transactions"
