
# Secured Properties
dynamodb:
  accesskey: "![n1z+OPkpA1Jsc+RzqqWMxyhKb+88ORWlzlCrkOMDuoo=]"
  secretkey: "![CdTrP88+5PVUwd9LLoWYt7mj4kCZn3WCjpmwFhx5I+q8FLN7pmysdfDuJ/aMQ0YZ]"
titan:
 sftp:
  username: "![ZibIQHduKBhWhwM1G4K8VA==]" 
  password: "![EO09WjxFFEVguFoFeXdW3A==]"

# ClientId and ClientSecret of digigoldOrderPAPI ## Final Client APP for digigold-order-papi. ## do not duplicate
digigold-order-papi: 
  clientId: "![WBrD6JW/RmSIv6EAk1Pl/p56Vi0kDFTVO5/sJrlP2g6pq2aTVX8MMLiy4Y69SA+z]"
  clientSecret: "![VMKloGwils2yctHfN8Fb27obH/xSBkFNAScdwbjME3oNvJQSRY1ttO0QLojXZ3WQ]"
  
aes:
  password: "![BKj8cVo3c9xUhGWQptxgCODmgNZJn1a3LvRUru4U6b0=]" 
  

dynamoOrderSapi:
  client_id: "![7HjVNfsJ/k9rhVrnlzozzTBV6+HDe11gS50B5lgxLGc8Y7rP4906NGxb20DzeW6l]"
  client_secret: "![oMTPhZ3m5V5dDGYYNiIfRCLP2BpkhhQF7v1J9CGirm9chL2DZpElhJ1t6N5KO/yG]"

# SFCC Order SAPI Client credentials
sfcc-order-sapi:
    client_id: "![VEv11Cx7VW9HcQH0svZcCW617c3lQ3ThdqZ/qqt6DB2/j0gkl9VBJ8Cw1G3wVo8i]"
    client_secret: "![NZkVQhtU0taX/1+LEDMxfEUgnct99QtEsvRJEH5l89Ws51XHoPgyPobJlXQchF48]"
    
notification-sapi:
    client_id: "![01hsmoN1YKR5/mUzXYGHRAw1c3pNsBqeyiZVoTndrwACh62299nmOA+ZD8u8r0bN]"
    client_secret: "![MnSbXTw6LlVSgm/J+uTMZdh+crvuF5y1qKPYl38d1kGglGFKp+JBAWlHFHSRnX7k]"
