name: UAT Manual Trigger - Workflow

#Triggers manually
#APPROVAL is needed for all the jobs to trigger !!!
on:
  workflow_dispatch:

jobs:

  #This job deploys the application to UAT environment with provided configuration details; upon APPROVAL from the aprrovers
  deploy-uat-01:
    uses: titandigitalecom/ms-devops-workflow/.github/workflows/deploy_workflow.yml@main
    with:
      CLOUDHUB_ENVIRONMENT: "UAT"
      GITHUB_ENVIRONMENT: "UAT"
      CLOUDHUB_REPLICAS: "${{ vars.MULE_CLOUDHUB_REPLICAS_1 }}"
      CLOUDHUB_REPLICA_SIZE: "${{ vars.MULE_CLOUDHUB_REPLICA_SIZE_0_1 }}"
      CLOUDHUB_PRIVATE_SPACE: "${{ vars.MULE_NONPROD_CLOUDHUB_PRIVATE_SPACE }}"
      CLOUDHUB_PUBLIC_URL: "" #Provide the Endpoint URL if custom public endpoint is needed
      GENERATE_PUBLIC_URL_FLAG: "false" #Set to true only if the app has public Endpoint URL; in all other cases this should be false
      APP_LAYER: ${{ vars.MULE_EXP_API_LAYER }}
    secrets:
      EX_CONNECTED_APP_ID: "${{ secrets.MULE_EX_CONNECTED_APP_ID }}"
      EX_CONNECTED_APP_SECRET: "${{ secrets.MULE_EX_CONNECTED_APP_SECRET }}"
      CH_CONNECTED_APP_ID: "${{ secrets.MULE_NONPROD_CH_CONNECTED_APP_ID }}"
      CH_CONNECTED_APP_SECRET: "${{ secrets.MULE_NONPROD_CH_CONNECTED_APP_SECRET }}"
      MULE_AP_CLIENT_ID: "${{ secrets.MULE_AP_CLIENT_ID }}"
      MULE_AP_CLIENT_SECRET: "${{ secrets.MULE_AP_CLIENT_SECRET }}"
      TITAN_BIZ_GROUP: "${{ secrets.MULE_TITAN_BIZ_GROUP }}"
      SECURE_ENCRYPT_KEY: "${{ secrets.MULE_UAT_SECURE_ENCRYPT_KEY }}"
